## 8.3 Promise 的基本使用

### 前言

- 时长：

> 再次强调一下，后边笔记中出现的 resolve 和 fulfill、resolved 和 fulfilled，我们将它们看做是一个东西即可。
>
> 笔记中的个别用词可能不是很准确，但是逻辑是没问题的。

- [x] 谈谈你对 Promise 的理解？
  Promise 并没有消除回调，只是通过一种特定的模式，让回调变得可控（让异步行为变得可控）。
- [ ] 下面哪种做法不能让 Promise 进入 rejected 状态？
  A. 在 Promise 构造函数的参数方法中抛出错误；
  B. 在 Promise 构造函数的参数方法中调用 reject()；
  C. 在 Promise 构造函数的参数方法中代码报错；
  D. 调用 Promise 的 catch 方法；√

### 概述

本节重点：
- 掌握如何将 `unsettled` 阶段的 Promise 推向 `settled` 阶段；
- 什么情况下是将 Promise 推向 `resolved` 状态；
- 什么情况下是将 Promise 推向 `rejected` 状态；

### thenable、catchable

```js
const pro = new Promise((resolve, reject)=>{
  // 这里是未决阶段的处理：
  // 通过调用 resolve 函数将 Promise 推向已决阶段的 resolved 状态；
  // 通过调用 reject 函数将 Promise 推向已决阶段的 rejected 状态；
  // resolve 和 reject 均可以传递最多一个参数，表示推向状态的数据；
})

pro.then(data => {
    // 这里是 thenable 函数：
    // 如果当前的 Promise 已经是 resolved 状态，该函数会立即执行；
    // 如果当前是未决阶段（pending 状态），则会加入到作业队列，等待到达 resolved 状态后执行；
    // data 为传入的状态数据
}, err => {
    // 这是 catchable 函数：
    // 如果当前的 Promise 已经是 rejected 状态，该函数会立即执行；
    // 如果当前是未决阶段（pending 状态），则会加入到作业队列，等待到达 rejected 状态后执行；
    // err 为传入的状态数据
})
```

1. 未决阶段的处理函数是同步的，会立即执行。
2. thenable 和 catchable 函数是异步的，就算是立即执行，也会加入到事件队列中等待执行，并且，加入的队列是微队列。
3. pro.then 可以只添加 thenable 函数，pro.catch 可以单独添加 catchable 函数。
   也可以同时添加 thenable（作为第一个参数传入）和 catchable（作为第二个参数传入）。
4. 在未决阶段（pending 状态）的处理函数中，如果发生未捕获的错误，会将状态推向 rejected，并会被 catchable 捕获，错误对象将作为 catchable 的参数传入。
5. 一旦状态推向了已决阶段，无法再对状态做任何更改。（状态改变不可逆）
6. Promise 并没有消除回调，只是让回调形成一种特定的模式，变得可控。

**Attention**

- thenable、catchable 函数中所说的“立即执行”，指的是将事件处理函数立即推向微队列（micro queue），必须要等到同步程序执行完后，它才会执行。

### codes

- [x] 1.js

```js
function biaoBai(god, callback) {
  console.log(`邓哥向女神【${god}】发出了表白短信`);
  setTimeout(() => {
    if (Math.random() < 0.1) {
      callback(true);
    } else {
      callback(false);
    }
  }, 1000);
}
```

- [x] 2.js

```js
/*
使用 Promise 来实现同样的逻辑
*/
const pro = new Promise((resolve, reject) => {
  console.log(`邓哥向女神1发出了表白短信`);
  setTimeout(() => {
    if (Math.random() < 0.1) {
      resolve(true);
    } else {
      resolve(false);
    }
  }, 1000);
});
/*
我们在 chrome 的控制台尝试输出 pro，查看当前状态；
分别在 ＜ 1s，和 ＞ 1s 两个时间点打印 pro：
*/
```

![20210418123722](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418123722.png)

注解

- 错误的理解：接受就是 resolve；拒绝就是 reject；
- 正确的理解：程序执行过程正常，没有发生错误，就是 resolve；发生了错误，就是 reject；

如果女神拒绝了，那么调用的应该是 resolve，因为这依旧是程序的正常逻辑，出现的是一个正常的结果，并没有出现“错误”，不会影响后续程序正常逻辑的执行。通常在出现错误的信息的时候，我们才会调用 reject 函数，将 promise 推向 rejected 状态。

简言之，出现错误，就调用 reject 函数，将 promise 推向 rejected 状态；否则，就意味着程序是正常执行的，调用 resolve 函数，将 promise 推向 resolved 状态。

- [x] 3.js

```js
/*
将之前封装的 ajax 的外层套上一层 promise：
*/
const pro = new Promise((resolve, reject) => {
  ajax({
    url: './data/students.json?name=李华',
    success(data) {
      resolve(data);
    },
    error(err) {
      reject(err);
    }
  });
});

pro.then((data) => {
  console.log(data);
});
```

调用 resolve 函数时，传入的参数将会作为 thenable 的参数传入：

![20211112134507](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20211112134507.png)

![20210418124730](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418124730.png)

当触发 thenable 函数的执行时，意味着 promise 已经进入了 resolved 状态：

![20210418124828](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418124828.png)

- [x] 4.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('unsettled');
  resolve('dahuyou');
});

pro.then((data) => {
  console.log(data);
});
/* 输出：
unsettled
dahuyou
*/
```

- [x] 5.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('unsettled');
  setTimeout(() => {
    resolve('dahuyou');
  }, 3000);
});

pro.then((data) => {
  console.log(data); // 3s 后才会打印
});
/*
unsettled
dahuyou
*/
```

- [x] 6.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('unsettled');
  setTimeout(() => {
    resolve('dahuyou');
  }, 3000);
});

pro.then((data) => {
  console.log(data + '1');
});
pro.then((data) => {
  console.log(data + '2');
});
pro.then((data) => {
  console.log(data + '3');
});

/* 输出：
unsettled
dahuyou1
dahuyou2
dahuyou3
并列的 Promise：为一个 Promise 注册多个 thenable，一旦该 Promise 的状态变为 resolved，那么会按照事件注册的顺序，执行多个 thenable 函数。
*/
```

注解

不要误以为 3 个 thenable 函数的执行是间隔 3s 的。它们都是一个 promise 身上的 thenable，一旦该 promise 的状态变为 resolved，那么就会执行 thenable 函数。它们几乎是同时执行的，但是执行的先后顺序是根据我们注册 thenable 的顺序来执行。

- [x] 7.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('unsettled');
  setTimeout(() => {
    if (Math.random() < 0.5) {
      resolve('dahuyou');
    } else {
      reject(new Error('dahuyou'));
    }
  }, 3000);
});

pro.then(data => {
  console.log('resolved');
  console.log(data + '1');
}, err => {
  console.log('rejected');
  console.log(err + '1');
});
pro.then(data => {
  console.log(data + '2');
}, err => {
  console.log(err + '2');
});
pro.then(data => {
  console.log(data + '3');
}, err => {
  console.log(err + '3');
});
/*
和 6.js 一样，都是并列的 promise。
*/
```

![20210427163725](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210427163725.png)
![20210427163732](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210427163732.png)


- [x] 8.js

```js
/*
在函数内部返回 promise
*/
function biaoBai(god) { // 返回一个 promise
  return new Promise((resolve, reject) => {
    console.log(`邓哥向【${god}】发出了表白短信`);
    setTimeout(() => {
      if (Math.random() < 0.1) {
        resolve(true);
      } else {
        resolve(false);
      }
    }, 3000);
  });
}
const pro = biaoBai('女神1');
pro.then(result => {
  console.log(result);
});
/*
最后的写法：
  const pro = biaoBai('女神1');
  pro.then(result => {
    console.log(result);
  });
其实可以改写为下面这样的形式：
  biaoBai('女神1').then(result => {
    console.log(result);
  });
会发现这么写的话，程序的可读性就很好。
向“女神1”表白，若程序逻辑正常（没有发生错误），那么将得到的结果 result 打印。
*/
```

![20210418130644](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418130644.png)
![20210418130723](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418130723.png)

- [x] 9.js

```js
// 改写 封装好的Ajax函数
function ajax(obj) {
  return new Promise((resolve, reject) => {
    // ... 保持不变
    // 接收返回过来的数据
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4) {
        if (xhr.status >= 200 && xhr.status < 300 || xhr.status == 304) {
          resolve(JSON.parse(xhr.responseText));
        } else {
          reject(xhr.status);
        }
      }
    }
  });
}

/*
// 原来的 ajax 函数
function ajax(obj) {
  // ...
  // 接收返回过来的数据
  xhr.onreadystatechange = function () {
    if (xhr.readyState === 4) {
      if (xhr.status >= 200 && xhr.status < 300 || xhr.status == 304) {
        if (obj.success) {
          // resolve
          obj.success(JSON.parse(xhr.responseText));
        }
      } else {
        if (obj.error) {
          // reject
          obj.error(xhr.status);
        }
      }
    }
  }
}
*/
```

```js
// 将 ajax 改写后，我们就可以按照下面这样的方式来调用 ajax。
ajax({
  url: './data/students.json?name=李华'
}).then(res => {
  console.log(res);
}, err => {
  console.log(err);
});
/*
可读性依旧很好：
调用 ajax 函数，向 './data/students.json?name=李华' 发出请求；
若正常拿到了数据，那么执行 thenable，将请求到的数据打印出来；
若请求过程中发生了错误，那么执行 catchable，将错误信息打印出来；
*/
```

![20210418131340](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418131340.png)

- [x] 10.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('a'); // 这里面的是同步执行的程序
});

console.log('b');
/*
unsettled 阶段的程序是同步的，会立即执行。
*/
```

![20210418131818](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418131818.png)

- [x] 11.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('a');
  resolve('dahuyou');
  console.log('b');
});

pro.then(data => {
  console.log(data);
})
/*
Promise 构造函数的参数方法中的代码，是同步执行的。
而 thenable 和 catchable 是异步的，就算是立即执行，也会加入到事件队列中等待执行，并且加入的是 微队列（micro queue）。
*/
```

![20210418132050](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418132050.png)
![20211112141212](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20211112141212.png)

同步代码必然是先于异步代码被执行，所以在控制台中会先打印 a、b 再打印 dahuyou。

- [x] 12.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('a'); // 同步
  resolve('dahuyou'); // 同步
  console.log('b'); // 同步
});

pro.then(data => {
  console.log(data); // 异步
})

console.log('c'); // 同步
```

![20210418132432](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418132432.png)

注解

虽然 resolve 函数是同步的，但是，thenable 是异步的。当 resolve 执行后，thenable 会立即执行，这句话本身是没错的。但是，由于它是异步的，它想要立即执行，还得等同步的执行完，才能轮到它。

- [x] 13.js

```js
const pro = new Promise((resolve, reject) => {
  console.log('a');
  resolve('dahuyou');
  setTimeout(() => {
    console.log('b'); // 异步 -> macro queue
  }, 0);
});

pro.then(data => {
  console.log(data); // 异步 -> micro queue
})

console.log('c');
/*
micro queue 优先于 macro queue
*/
```

![20210418132557](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418132557.png)

注解

虽然 thenable 和 setTimeout 都是异步的，但是它们是不同的，微队列（micro queue）和宏队列（macro queue）中的都有东西的话，执行栈（call stack）会优先关顾 micro queue 中的内容。所以，dahuyou 会先于 b 被打印。

- [x] 14.js

```js
pro.then(data => {
  console.log(data);
}, err => {
  console.log(err);
});

// 下面是等效写法：

pro.then(data => {
  console.log(data);
});
pro.catch(err => {
  console.log(err);
});
/* Promise.then() 和 Promise.catch()
pro.then 可以只添加 thenable（仅写一个参数即可），也可以同时添加 thenable 和 catchable（同时写两个参数即可）。
使用 pro.catch 只可以添加 catchable。
*/
```

- [x] 15.js

```js
const pro = new Promise((resolve, reject) => {
  throw new Error('抛出一个错误'); // pro -> rejected
});

pro.then(data => {
  console.log(data);
}, err => {
  console.log(err);
});
/*
在 unsettled 阶段的处理函数中，若发生了未捕获的错误：
  将 promise 的状态推向 rejected，并会被 catchable 捕获，执行 catchable。
*/
```

![20210418133329](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418133329.png)

- [x] 16.js

```js
const pro = new Promise((resolve, reject) => {
  resolve(1);
  reject(2); // 无效
  resolve(3); // 无效
});

pro.then(data => {
  console.log(data);
}, err => {
  console.log(err);
});
/*
promise 状态是不可逆的：
  一旦 promise 的状态推向了 settled 状态，无法再对它的状态做任何更改。
最终输出结果只有一个 1
*/
```

- [x] 17.js

```js
const pro = new Promise((resolve, reject) => {
  throw new Error('抛出一个错误'); // pro -> rejected
  resolve(1); // 无效
});

pro.then(data => {
  console.log(data);
}, err => {
  console.log(err);
});
/*
未捕获的错误，会将 promise 推向 settled 阶段。
*/
```

![20210418133731](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418133731.png)

- [x] 18.js

```js
const pro = new Promise((resolve, reject) => {
  try {
    throw new Error('抛出一个错误');
  } catch {
    console.log('捕获到了错误');
  }
  resolve(1); // 有效 因为上面的错误被捕获了 并没有将 pro 的状态推向 rejected
});

pro.then(data => {
  console.log(data);
}, err => {
  console.log(err);
});
/*
被捕获的错误，并不会将 promise 推向 settled 阶段。
*/
```

![20210418133936](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418133936.png)

- [x] 19.js

```js
const pro = new Promise((resolve, reject) => {
  const a = 1;
  a = 2; // 报错，因为常量无法被重新赋值。
});

pro.then(result => {
  console.log(result);
});

pro.catch(err => {
  console.log(err);
});
/*
在 Promise 构造函数的参数方法中，若代码报错：会将该 Promise 推向 rejected 状态。
*/
```

![20210510220730](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210510220730.png)
