## 8.4 Promise的串联

### 前言

- 时长：

### promise 的串联

当后续的 Promise 需要用到之前的 Promise 的处理结果时，需要 Promise 的串联。

以前面我们写过的查询李华老师信息的 demo 为例：
1. 先通过学生姓名：“李华”，查询到指定学生信息；
2. 在查询到的学生信息中，可以读取到该学生所在的班级 id，再通过该 id 查询到指定班级信息；
3. 在查询到的班级信息中，可以读取到该班级的老师的 id，最后通过该 id 获取到指定老师信息；

会发现，上面这一系列的操作，是有一定的先后次序的。后续操作需要依赖前面操作得到的结果数据，对于类似这样的操作，我们就需要使用到 promise 的串联。

### thenable、catchable

Promise 对象中，无论是 then 方法还是 catch 方法，它们都具有返回值，返回的是一个全新的 Promise 对象，它的状态满足下面的规则：

1. 如果当前的 Promise 是未决 unsettled 的，得到的新的 Promise 是挂起状态 pending；
2. 如果当前的 Promise 是已决 settled 的，得到的新的 Promise 的状态可能是 rejected 或 resolved，并会运行相应的后续处理函数①；
   - resolved：当前的 Promise 执行时，没有发生错误，执行新的 Promise 对象的 thenable（then 方法）；
   - rejected：当前的 Promise 执行时，发生了错误，执行新的 Promise 对象的 catchable（catch 方法）；

![20211112210123](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20211112210123.png)

```js
new Promise((resolve, reject) => {
  // ...
}).then(() => {
  // ...
}).catch(() => {
  // ...
})
```

当执行 thenable 时，

并将后续处理函数的结果②，作为 resolved 的状态数据，应用到新的 Promise 中；如果后续处理函数发生错误，则把返回值作为 rejected 的状态数据，应用到新的 Promise 中；


> ① => 若没有相应的后续处理函数来处理，那么返回的新的 Promise 对象的状态和数据都将与 当前的 Promise 对象保持一致；











> then 返回的 promise 对象 一开始一定是 pending 状态 `因为 then 中的程序是异步的, 要等到这些异步的程序有了执行结果之后, 返回的 Promise 对象才会被推向 settled 阶段; 但是并非 要等到前面的 Promise 有了处理结果才会返回 Promise 对象, 只要执行到 Promise.then() 语句时, 就会返回 Promise 对象, 即便 then 里面的异步程序都还没有开始执行, 即: 前一个Promise还没处理完, 没有返回处理结果; 所以说 then 返回的 Promise 对象一开始一定是 pending 状态, 因为里面的异步程序还没执行`
> **重点: unsettled 阶段的 pending 状态的程序是同步执行的。**

**后续的Promise一定会等到前面的Promise有了后续处理结果后，才会变成已决状态**

如果前面的Promise的后续处理，返回的是一个Promise，则返回的新的Promise状态和后续处理返回的Promise状态保持一致。

### codes

- [x] 1.html

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>回调地狱 - 3</title>
</head>

<body>
  <script src="./utils/ajax.promise.js"></script>
  <script>
    ajaxPromise({
      url: './data/students.json'
    }).then(stus => {
      for (let i = 0; i < stus.length; i++) {
        const stu = stus[i];
        if (stu.name === '李华') {
          const cid = stu.classId;
          console.log(`拿到李华所在的班级id: ${cid}`);
          ajaxPromise({
            url: './data/classes.json'
          }).then(cls => {
            for (let i = 0; i < cls.length; i++) {
              const cl = cls[i];
              if (cl.id === cid) {
                const tid = cl.teacherId;
                console.log(`拿到班级id为: ${cid} 的老师id: ${tid}`);
                ajaxPromise({
                  url: './data/teachers.json'
                }).then(ts => {
                  for (let i = 0; i < ts.length; i++) {
                    const t = ts[i];
                    if (t.id === tid) {
                      console.log(`拿到老师id为: ${tid} 的老师信息: `, t);
                    }
                  }
                });
              }
            }
          });
        }
      }
    });
    /*
    试着用目前所学到的内容，尝试重新写一遍回调地狱 3 的那个 demo。
    会发现：即便使用现阶段所学的 Promise 的相关知识点，依旧没有解决 8.1 中提及的“回调地狱”的问题。
    */
  </script>
</body>

</html>
```

![20210510222246](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210510222246.png)

- [x] 2.js

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>回调地狱 - 3</title>
</head>

<body>
  <script src="./utils/ajax.promise.js"></script>
  <script>
    const pro = ajaxPromise({
      url: './data/students.json'
    });

    // 获取指定学生信息
    pro.then(stus => {
      stus.forEach(stu => {
        if (stu.name === '李华') {
          console.log(`获取到的李华学生信息如下:`);
          console.log(stu);
        }
      });
    });

    // 获取所有的女生
    pro.then(stus => {
      const newArr = stus.filter(stu => stu.gender === '女');
      console.log(`获取到的所有女生信息如下:`);
      console.log(newArr);
    });

    // 获取所有年龄在 20 岁以下的学生信息
    pro.then(stus => {
      const newArr = stus.filter(stu => stu.age < 20);
      console.log(`获取到的所有年龄在 20岁 以下的学生信息如下:`);
      console.log(newArr);
    });
    /*
    并列的 promise
    上面涉及到的是 同一个 promise 的并列操作
    - 获取指定学生信息
    - 获取所有的女生
    - 获取所有年龄在 20 岁以下的学生信息
    这3个需求 是并列进行的 它们之间并没有什么先后关系
    即: 后续操作不需要依赖前面操作得到的结果数据
    */
  </script>
</body>

</html>
```

![20210510222713](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210510222713.png)

thenable 接收到的参数 stus 中的数据：

![20210418150543](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418150543.png)




- [x] demo

`then 返回的 promise 对象一开始一定是 pending 状态`

```js
const pro1 = new Promise((resolve, reject) => {
    resolve(1);
});
console.log(pro1);
const pro2 = pro1.then(result => result * 2);
console.log(pro2);
/* 输出的 pro2
类型是: promise对象
状态是: pending
    因为输出pro2时 pro1.then 中的异步程序还没有开始执行
    要等到 pro1.then 中的异步程序执行完后 也就是 pro1 有了处理结果后 pro2 的状态才会变为 resolved 并且 pro1 的处理结果将作为 pro2 的状态数据传入
 */
pro2.then(result => console.log(result), err => console.log(err)); // 2
```

![20210511170805](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210511170805.png)

```
在执行同步语句 console.log(pro2); 时 pro1.then(result => result * 2); 中的异步语句 result => result * 2 还没有执行 即: pro1.then 还没有得到一个处理结果
```

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    resolve(1);
});

const pro2 = pro1.then(result => result * 2);
console.log(pro2);

setTimeout(() => {
    console.log(pro2);
}, 0);
```

![20210426144856](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210426144856.png)

```
pro1.then() 返回的 promise 对象的状态会 动态更新 并不是一成不变的 只要 pro1.then() 有了处理结果 那么它返回的 promise 对象的状态就会变为 settled 阶段
```

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    throw 1; // A 出错了
});

const pro2 = pro1.then(result => result * 2, err => err * 3); // B 没有出错
// 因为 A 出错了 所以 B 运行 catchable 即: err => err * 3

pro2.then(result => console.log(result * 2), err => console.log(err * 3)); // C
// 因为 B 没有出错 所以 C 运行 thenable 即: result => console.log(result * 2)
```

![20210426145929](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210426145929.png)

```
const promise1 = new Promise((resolve, reject) => {
    // ... pending 阶段的事件处理程序
});
promise2 = promise1.then(thenable, catchable);

promise1 和 promise2 的状态分析

promise1 的状态 取决于 在 pending 阶段的事件处理程序中 执行的是 resolve() 还是 reject() 还是 抛出了错误
    执行 resolve() ==> promise1 变为 resolved 状态 ==> 执行 thenable
    执行 reject() 或 抛出错误 ==> promise1 变为 rejected 状态 ==> 执行 catchable
promise2 的状态 取决于 promise1.then() 执行是否抛出了错误
    没有抛出错误 ==> promise2 变为 resolved 状态
    抛出了错误 ==> promise2 变为 rejected 状态
```

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    throw 1;
});

const pro2 = pro1.then(result => result * 2, err => {
    throw err;
} );

pro2.then(result => console.log(result * 2), err => console.log(err * 3)); // 3
```

![20210418165448](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418165448.png)

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    throw 1;
});

const pro2 = pro1.then(result => result * 2, err => {
    throw err;
});

pro2.catch(err => err * 5);

pro2.then(result => console.log(result * 3), err => console.log(err * 4)); // 4
```

![20210418170013](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418170013.png)

```
pro2.catch();
pro2.then();
// 注意: 最后两个条语句 它们是并列关系 两者之间互不影响 并不会出现覆盖的情况
```

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    throw 1;
});

const pro2 = pro1.then(result => result * 2, err => {
    console.log(err); // 1
    throw err;
});

pro2.catch(err => {
    console.log(err * 5); // 5
});

pro2.then((result) => {
    console.log(result * 3);
}).catch((err) => {
    console.log(err * 4); // 4
});
```

![20210511173650](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210511173650.png)

```
两者之间是并列关系 并不会出现覆盖的情况
```

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    throw 1;
});

const pro2 = pro1.then(result => result * 2, err => {
    console.log(err); // 1
    throw err * 2;
});

pro1.catch(err => {
    console.log(err); // 1
    throw err;
});

pro2.then((result) => {
    console.log(result * 3);
}).catch((err) => {
    console.log(err * 4); // 8
});
```

```
两者之间是并列关系 并不会出现覆盖的情况
```

- [x] demo

`在 thenable 或 catchable 中返回的是一个 promise 对象`

```js
const pro1 = new Promise((resolve, reject) => {
    resolve(1);
});

const pro2 = new Promise((resolve, reject) => {
    resolve(2);
});

const pro3 = pro1.then(result => {
    return pro2;
});

console.log(pro3); // Promise {<pending>}
console.log(pro3 === pro2); // false

pro3.then(result => {
    console.log(result === pro2); // false
    console.log(result); // 2
});

pro2.then(result => {
    console.log(result * 2); // 2
});
```

![20210511174500](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210511174500.png)

`如果前面的Promise的后续处理，返回的是一个Promise，则返回的新的Promise状态和后续处理返回的Promise状态保持一致。`

```
这句话指的是 pro3 的状态 与 pro2 的状态保持一致
    当 pro2 的状态变为 resolved 之后 pro3 才会变为 resolved
    当 pro2 的状态变为 rejected 之后 pro3 才会变为 rejected
    并且两者的参数还相同
[注] 一定是 pro2 先发生状态变化, pro3 后发生状态变化, 所以我们会看到, 控制台中先打印的是 4, 后打印的是 2
```

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    resolve(1);
});

const pro2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve(2);
    }, 3000);
});

const pro3 = pro1.then(result => {
    return pro2;
});

pro3.then(result => {
    console.log(result); // 2
});
```

```
3s 后 会在控制台打印 2
虽然 pro1.then() 很快就返回了一个处理结果 按理来说 pro3 在 pro1.then() 得到一个处理结果后 就将变为 settled 阶段; 但是这里有点特殊, 因为返回的是一个 promise 对象 pro2, 所以 pro3 的状态将由 pro2 来决定, 只有当 pro2 的变为 settled 阶段 pro3 才会变为 settled 阶段
```

- [x] demo

```js
const pro1 = new Promise((resolve, reject) => {
    resolve(1);
});

const pro2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve(2);
    }, 3000);
});

pro1.then(result => {
    console.log(1); // 1
    return pro2;
}).then(result => { // 要等到 pro2 变为 resolved 状态之后 才会执行
    console.log(result); // 2
    // return undefined; // 没有写 return 默认返回 undefined
}).then(result => {
    console.log(result); // undefined
});
```

![20210418171922](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418171922.png)

```
立即打印 1
过 3s 后 打印 2 和 undefined
因为第二个 then 中并没有 指定 return 的返回值
所以 return 默认值 undefined
```

**下面开始尝试使用串联的 Promise 来重写 8.1 中的 demo3**

- [x] bug

`经典的 错误写法... 为什么控制台啥也没打印`

```js
const pro = ajax({
    url: './data/students.json'
});

// 查找李华的老师信息
pro.then(res => {
    let cId = null; // 班级id

    // 给 cId 赋值
    res.forEach(stu => {
        if (stu.name === '李华') {
            cId = stu.classId;
        }
    });

    return cId; // 作为下一次的 thenable 参数传入
}).then(cId => {
    let tId = null; // 老师id

    // 给 tId 赋值
    ajax({
        url: './data/classes.json?classId=' + cId
    }).then(classRoom => {
        classRoom.forEach(c => {
            if (c.id === cId) {
                tId = c.teacherId;
            }
        });
        // console.log(tId);
    });

    // console.log(tId);
    return tId;
}).then(tId => {
    ajax({
        url: './data/teachers.json?teacherId=' + tId
    }).then(teacher => {
        teacher.forEach(t => {
            if (t.id === tId) {
                console.log(t);
            }
        });
    });
});
```

```
这个 bug 的原因其实是由于 异步函数 所导致的
将这段程序中的两条被注释掉的打印语句 console.log(tId); 取消掉注释
会发现控制台先输出的将会是 下面一行打印语句输出的 tId 结果为 null
相对于第二次调用 ajax 而言 代码 let tId = null; 和 return tId; 是同步执行的; 而 ajax().then(...) 中的 thenable程序是异步执行的

[原因分析] ajax().then(异步执行的程序) then方法中的程序是异步执行的
```

`执行顺序分析`

```js
const pro = ajax({
    url: './data/students.json'
});

// 查找李华的老师信息
pro.then(res => {
    let cId = null; // 班级id

    // 给 cId 赋值
    res.forEach(stu => {
        if (stu.name === '李华') {
            cId = stu.classId;
        }
    });

    return cId; // 作为下一次的 thenable 参数传入
}).then(cId => {
    let tId = null; // 老师id

    console.log(1);

    ajax({
        url: './data/classes.json?classId=' + cId
    }).then(classRoom => {

        console.log(5);

        classRoom.forEach(c => {
            if (c.id === cId) {
                tId = c.teacherId;
            }
        });
    });

    console.log(2);

    return tId;
}).then(tId => {

    console.log(3);

    ajax({
        url: './data/teachers.json?teacherId=' + tId
    }).then(teacher => {

        console.log(6);

        teacher.forEach(t => {
            if (t.id === tId) {
                console.log(t);
            }
        });
    });

    console.log(4);
});
```

![20210420174402](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210420174402.png)

- [x] debug - 1 `then 方法返回的不是一个 promise 对象`

```js
const pro = ajax({
    url: './data/students.json'
});

// 查找李华的老师信息
pro.then(res => {
    let cId = null; // 班级id

    // 给 cId 赋值
    res.forEach(stu => {
        if (stu.name === '李华') {
            cId = stu.classId;
        }
    });

    return cId; // 作为下一次的 thenable 参数传入
}).then(cId => {

    ajax({
        url: './data/classes.json?classId=' + cId
    }).then(classRoom => {
        let tId = null; // 老师id

        // 给 tId 赋值
        classRoom.forEach(c => {
            if (c.id === cId) {
                tId = c.teacherId;
            }
        });

        return tId;
    }).then(tId => {

        ajax({
            url: './data/teachers.json?teacherId=' + tId
        }).then(teacher => {
            teacher.forEach(t => {
                if (t.id === tId) {
                    console.log(t);
                }
            });
        });

    });
});
```

![20210418154035](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418154035.png)

```
这么做虽然获取到了想要的结果, 但是还是会陷入回调地狱;
```

- [x] debug - 2 `then 方法返回的是一个 promise 对象`

```
PS: 此时没用调通 最终控制台输出的结果是 undefined 试分析原因...
```

```js
const pro = ajax({
    url: './data/students.json'
});

// 查找李华的老师信息
pro.then(res => {
    res.forEach(stu => {
        if (stu.name === '李华') {
            return stu.classId; // 将学生对应的班级id返回 作为一下次处理函数的参数传入
        }
    });
}).then(cId => {
    return ajax({
        url: './data/classes.json?classId=' + cId
    }).then(classRoom => {
        classRoom.forEach(c => {
            if (c.id === cId) {
                return c.teacherId; // 将班级对应的老师id返回 作为一下次处理函数的参数传入
            }
        });
    });
}).then(tId => {
    return ajax({
        url: './data/teachers.json?teacherId=' + tId
    }).then(teacher => {
        teacher.forEach(t => {
            if (t.id === tId) {
                return t; // 将老师信息返回 作为一下次处理函数的参数传入
            }
        });
    });
}).then(tInfo => {
    console.log(tInfo); // undefined
});
```

```
forEach 它也是一个函数, 所以 return 不能在 forEach 这个函数里面 return
```

- [x] debug - 3

`把 forEach 改成 for 循环即可`

```js
const pro = ajax({
    url: './data/students.json'
});

// 查找李华的老师信息
pro.then(res => {
    for (let i = 0; i < res.length; i++) {
        const stu = res[i];
        if (stu.name === '李华') {
            return stu.classId; // 将学生对应的班级id返回 作为一下次处理函数的参数传入
        }
    }
}).then(cId => {
    return ajax({
        url: './data/classes.json?classId=' + cId
    }).then(classRooms => {
        for (let i = 0; i < classRooms.length; i++) {
            const c = classRooms[i];
            if (c.id === cId) {
                return c.teacherId; // 将班级对应的老师id返回 作为一下次处理函数的参数传入
            }
        }
    });
}).then(tId => {
    return ajax({
        url: './data/teachers.json?teacherId=' + tId
    }).then(teachers => {
        for (let i = 0; i < teachers.length; i++) {
            const t = teachers[i];
            if (t.id === tId) {
                return t; // 将老师信息返回 作为一下次处理函数的参数传入
            }
        }
    });
}).then(tInfo => {
    console.log(tInfo); // {id: 2, name: "张", gender: "女"}
});
```

```
这种写法实际上还可以进一步简化 不过得掌握后续的更多知识点之后 才能实现...
```

- [x] demo

`用 promise 来实现 8.1 的 demo2`

```
需求描述:
    场景:
      邓哥心中有三个女神
      有一天，邓哥决定向第一个女神表白
      如果女神拒绝，则向第二个女神表白
      直到所有的女神都拒绝 或 有一个女神同意为止
      表白的时间间隔为 1s
    用代码模拟上面的场景
```

```js
function biaoBai(god) {
    return new Promise((resolve, reject) => {
        console.log(`邓哥向${god}发出了表白短信`);
        setTimeout(() => {
            if (Math.random() < 0.1) {
                resolve(true); // 女神同意了
            } else {
                resolve(false); // 女神拒绝了
            }
        }, 1000); // 等 1s 后再决定该 promise 的状态
    });
}

biaoBai('女神1').then(result => {
    if (result === true) {
        console.log('女神1同意了 停止表白');
        return;
    } else {
        console.log('女神1拒绝了 继续向女神2表白');
        return biaoBai('女神2');
    }
}).then(result => {
    if (result === undefined) { // 女神1同意了 接下来啥也不做
        return;
    } else if (result === true) {
        console.log('女神2同意了 停止表白');
        return;
    } else {
        console.log('女神2拒绝了 继续向女神3表白');
        return biaoBai('女神3');
    }
}).then(result => {
    if (result === undefined) { // 女神1 或 女神2 同意了 接下来啥也不做 (result === undefined 表示在此之前已经有女神同意了)
        return;
    } else if (result === true) {
        console.log('女神3同意了 停止表白');
    } else {
        console.log('女神3拒绝了 全都拒绝了');
    }
});
```

![20210418183744](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418183744.png)

![20210418183816](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418183816.png)

```
下一个 then 执行所接收的参数 主要看前一个 then 的return 是啥
这个案例中 return 只有两种情况
    1. undefined
    2. Promise -> 注意 返回的 promise 对象 并非作为后续的 then 的数据
假设
    女神1 同意了
    那么 程序执行的时间大致在 1s 左右, 因为之后的 then 接收到的都是 undefined 返回的也都是 undefined
同理
    女神1 拒绝 女神2 同意 执行 2s 左右
    女神1 和 女神2 都拒绝 执行 3s 左右
```

- [x] demo

**思考:**

`pro = pro.then(...)` 为什么这么写就能实现 pro 的串联, pro 变量明明就只有一个, 重复赋值 为什么不会覆盖前面的值?

`简化版 提取公共 code 用for循环来实现`

```js
// const godsArr = ['女神1', '女神2', '女神3'];
const godsArr = ['女神1', '女神2', '女神3', '女神4', '女神5'];
let pro;

for (let i = 0; i < godsArr.length; i++) {
    const god = godsArr[i];
    if (i === 0) { // 第一次进入循环 先确保变量 pro 存放的是一个 promise 对象
        pro = biaoBai(god);
    }
    pro = pro.then(result => {
        if (result === true) {
            console.log(`${god}同意了 停止表白`);
            return;
        } else if (result === undefined) { // 已经有女神同意了 接下来啥也不做
            return;
        } else {
            if (god !== godsArr[godsArr.length - 1]) {
                console.log(`${god}拒绝了 继续向${godsArr[i + 1]}表白`);
                return biaoBai(godsArr[i + 1]);
            } else {
                console.log(`${god}拒绝了 全都拒绝了`);
            }
        }
    });
}
```

![20210418185355](https://cdn.jsdelivr.net/gh/123taojiale/dahuyou_picture@main/blogs/20210418185355.png)

```
先执行完的 肯定是 for 循环 执行完 for 循环后 相当于创建了下面这样的 'promise 链条', 该链条仅仅是创建好了, 但是then中的异步程序的执行 并不是在创建好后 就立即执行的
```

```js
biaoBai('女神1').then(result => {
    if (result === true) {
        console.log('女神1同意了 停止表白');
        return;
    } else {
        console.log('女神1拒绝了 继续向女神2表白');
        return biaoBai('女神2');
    }
}).then(result => {
    if (result === undefined) {
        return;
    } else if (result === true) {
        console.log('女神2同意了 停止表白');
        return;
    } else {
        console.log('女神2拒绝了 继续向女神3表白');
        return biaoBai('女神3');
    }
}).then(result => {
    if (result === undefined) {
        return;
    } else if (result === true) {
        console.log('女神3同意了 停止表白');
    } else {
        console.log('女神3拒绝了 继续向女神4表白');
        return biaoBai('女神4');
    }
}).then(result => {
    if (result === undefined) {
        return;
    } else if (result === true) {
        console.log('女神4同意了 停止表白');
    } else {
        console.log('女神4拒绝了 继续向女神5表白');
        return biaoBai('女神5');
    }
}).then(result => {
    if (result === undefined) {
        return;
    } else if (result === true) {
        console.log('女神5同意了 停止表白');
    } else {
        console.log('女神5拒绝了 全都拒绝了');
    }
});
```

```
每次 pro 被赋予的都是一个 promise 对象 ———— 由上一个 pro.then 返回的全新的 promise 对象, 所以 并不会出现覆盖的情况
问: 表白结束后 pro 的状态和值分别是什么?
答: resolved undefined
```

- [ ] `补充`

`注意下面这句话, 在手写 Promise 那一节的最后一个视频中讲的 bug 就是该问题`

如果当前的Promise是已决`settled`的，会运行相应的后续处理函数`若没有相应的后续处理函数来处理 那么返回的新的 Promise 对象的状态和数据都将与 当前的 Promise 对象保持一致`

```js
const pro1 = new Promise((resolve, reject) => {
    resolve(1);
});

const pro2 = pro1.catch(err => {
    console.log(err); // 并不会执行
});

console.log(pro2 === pro1); // false
/*
pro1 和 pro2 的状态都是 resolved(fulfilled) 状态, 状态数据都是 1
*/

pro2.then(data => {
    console.log(data); // 1
});
```
